#!/usr/bin/env python3
"""
Microcode-driven emulator matching the hardware control-signal architecture.
Reads microcode_table.csv (generated by microcode_rom_gen.py), assembles a
test program, and executes it with optional cycle-level tracing.

Usage:
    python3 emulator.py [program.asm] [-v] [--trace-micro]

Architecture notes (from the hardware/schematic):
  - 8-bit data bus, single-cycle micro-steps
  - 4 general-purpose registers: R0–R3 (writes always go to Rd; reads
    select Rd or Rs via RS_SEL)
  - 8-bit MAR, 8-bit PC, 8-bit IR, A/TEMP staging registers
  - Harvard memory: program ROM (256 B), data SRAM (256 B)
  - ALU: add/subtract only, Z and C flags
  - Microcoded control: ROM addressed by (opcode[3:0], step[1:0], Z, C)
  - Instruction encoding:
      reg-reg (1 byte):  [opcode:4][Rd:2][Rs:2]
      addr    (2 bytes): [opcode:4][Rd:2][xx:2] [addr]
      For JMP/JZ/JC the register field is unused (set to 0)
"""

import csv
import os
import re
import sys
from pathlib import Path

OPCODES = {
    0b0000: "NOP",  0b0001: "LOAD",  0b0010: "STORE", 0b0011: "ADD",
    0b0100: "SUB",  0b0101: "JMP",   0b0110: "JZ",    0b0111: "JC",
    0b1000: "MOV",  0b1111: "HLT",
}
MNEMONIC_TO_OP = {v: k for k, v in OPCODES.items()}

# Reg-reg opcodes use Rd/Rs in the low nibble
REG_REG_OPCODES = {MNEMONIC_TO_OP[m] for m in ("ADD", "SUB", "MOV")}
# Address-format opcodes (2 bytes)
ADDR_OPCODES = {MNEMONIC_TO_OP[m] for m in ("LOAD", "STORE", "JMP", "JZ", "JC")}

DATA_RAM_SIZE = 256         # HM6116 with A8-A10 tied low
PROG_ROM_SIZE = 256         # 28C64 with A8-A12 tied low
NUM_STEPS = 4               # 2-bit step counter

#
#  CPU
#

class CPU:
    """Cycle-accurate 8-bit CPU emulator driven by the microcode table."""

    def __init__(self):
        self.regs = [0, 0, 0, 0]   # R0–R3
        self.pc    = 0              # 8-bit program counter
        self.mar   = 0              # 8-bit memory address register
        self.ir    = 0              # 8-bit instruction register
        self.a     = 0              # ALU A staging register
        self.temp  = 0              # ALU B (TEMP) staging register
        self.flag_z = 0
        self.flag_c = 0
        self.halted = False

        self.prog_rom = bytearray(PROG_ROM_SIZE)
        self.data_ram = bytearray(DATA_RAM_SIZE)
        self.ctrl_rom = {}          # addr → {signal_name: True}

        self.bus      = 0           # current bus value (for debug)
        self.step     = 0           # micro-step counter (0–3)
        self.cycles   = 0           # total micro-steps executed
        self.instr_count = 0        # total instructions executed

    # Microcode table

    def load_microcode(self, path: str):
        """Parse microcode_table.csv → self.ctrl_rom."""
        with open(path, newline="") as f:
            for row in csv.DictReader(f):
                addr = int(row["address"])
                raw = row["signals"].strip()
                if raw == "(none)":
                    self.ctrl_rom[addr] = frozenset()
                else:
                    self.ctrl_rom[addr] = frozenset(s.strip() for s in raw.split("+"))
        if len(self.ctrl_rom) != 256:
            print(f"[warn] microcode table has {len(self.ctrl_rom)} entries (expected 256)")

    #  Instruction encoding helpers

    @staticmethod
    def _reg_field(ir, use_rs: bool) -> int:
        """Extract 2-bit register index from IR: Rd = bits[3:2], Rs = bits[1:0]."""
        return (ir & 0b11) if use_rs else ((ir >> 2) & 0b11)

    #  ALU

    @staticmethod
    def _alu(a: int, b: int, su: bool) -> tuple:
        """
        Adder/subtractor: A + (B XOR SU) + SU, as built from '283 + '86.
        Returns (result, carry_out); for SUB, C=1 means no borrow (A >= B).
        """
        s = a + ((b ^ 0xFF) if su else b) + (1 if su else 0)
        return s & 0xFF, s >> 8

    #  Single micro-step

    def _tick(self, verbose=False):
        """Execute one micro-step, return True if the CPU just halted."""
        #  Look up control word
        opcode = (self.ir >> 4) & 0xF
        addr = (opcode << 4) | (self.step << 2) | (self.flag_z << 1) | self.flag_c
        sigs = self.ctrl_rom.get(addr, frozenset())

        #  Register select: reads use Rd or Rs, writes always use Rd
        use_rs = "RS_SEL" in sigs
        reg_idx = self._reg_field(self.ir, use_rs)
        wr_idx = self._reg_field(self.ir, False)

        #  ALU computation (always runs, result used only if EO asserted)
        alu_result, alu_carry = self._alu(self.a, self.temp, "SU" in sigs)

        # Bus arbitration (exactly one source may drive the bus)
        drivers = [d for d in ("IROM_OUT", "RAM_OUT", "REG_OUT", "EO") if d in sigs]
        if len(drivers) > 1:
            raise RuntimeError(f"bus contention at [{addr:02X}]: {drivers}")
        bus_val = 0
        if "IROM_OUT" in sigs:
            bus_val = self.prog_rom[self.pc]
        if "RAM_OUT" in sigs:
            bus_val = self.data_ram[self.mar & (DATA_RAM_SIZE - 1)]
        if "REG_OUT" in sigs:
            bus_val = self.regs[reg_idx]
        if "EO" in sigs:
            bus_val = alu_result
        self.bus = bus_val

        #  Latch (clock inputs)
        if "IR_IN" in sigs:
            self.ir = bus_val & 0xFF
        if "MAR_IN" in sigs:
            self.mar = bus_val & 0xFF
        if "REG_IN" in sigs:
            self.regs[wr_idx] = bus_val & 0xFF
        if "A_IN" in sigs:
            self.a = bus_val & 0xFF
        if "TEMP_IN" in sigs:
            self.temp = bus_val & 0xFF
        if "RAM_IN" in sigs:
            self.data_ram[self.mar & (DATA_RAM_SIZE - 1)] = bus_val & 0xFF
        if "PC_INC" in sigs:
            self.pc = (self.pc + 1) & 0xFF
        if "PC_LOAD" in sigs:
            self.pc = self.mar

        #  Flags
        if "FI" in sigs:
            self.flag_z = 1 if alu_result == 0 else 0
            self.flag_c = alu_carry

        #  Halt
        halted = "HLT" in sigs
        if halted:
            self.halted = True

        if verbose:
            self._print_micro_step(addr, sigs, bus_val, reg_idx, use_rs)

        self.step = (self.step + 1) % NUM_STEPS   # 2-bit counter wraps 0–3
        self.cycles += 1
        return halted

    #  Instruction-level execution

    def run(self, max_cycles=100_000, verbose=False, trace_micro=False):
        """Run until HLT or max_cycles reached. Returns True if halted cleanly."""
        while not self.halted and self.cycles < max_cycles:
            # Save state before this instruction (for instruction-level trace)
            pc_before = self.pc
            ir_before = self.ir
            regs_before = list(self.regs)
            z_before = self.flag_z
            c_before = self.flag_c

            # Execute all micro-steps for this instruction cycle
            for _ in range(NUM_STEPS):
                if self._tick(verbose=trace_micro):
                    break

            self.instr_count += 1

            if not trace_micro:
                self._print_instr_trace(pc_before, ir_before, regs_before,
                                        z_before, c_before)

        if self.cycles >= max_cycles:
            print(f"\n*** Halting after {max_cycles} micro-steps (cycle limit) ***")
        return self.halted

    # Disassembly helper

    @staticmethod
    def _disasm(prog_rom, pc) -> str:
        """Return a human-readable disassembly of the instruction at `pc`."""
        b0 = prog_rom[pc & 0xFF]
        op = (b0 >> 4) & 0xF
        rd = (b0 >> 2) & 0b11
        rs = b0 & 0b11
        mnemonic = OPCODES.get(op, f"(0b{op:04b})")

        if op == 0b0000:
            return "NOP"
        if op == 0b1111:
            return "HLT"
        if op in REG_REG_OPCODES:
            return f"{mnemonic} R{rd}, R{rs}"
        if op in ADDR_OPCODES:
            addr = prog_rom[(pc + 1) & 0xFF]
            if op in (0b0101, 0b0110, 0b0111):   # JMP / JZ / JC
                return f"{mnemonic} 0x{addr:02X}"
            return f"{mnemonic} R{rd}, 0x{addr:02X}"
        return f".byte 0x{b0:02X}"

    @staticmethod
    def _instr_size(b0: int) -> int:
        op = (b0 >> 4) & 0xF
        if op in ADDR_OPCODES:
            return 2
        return 1

    # Trace printing

    def _print_instr_trace(self, pc, ir, regs_before, z, c):
        disasm = self._disasm(self.prog_rom, pc)
        r = self.regs
        flags = f"Z={self.flag_z} C={self.flag_c}"
        print(f"  0x{pc:02X}  {disasm:<24s}  "
              f"R0={r[0]:02X} R1={r[1]:02X} R2={r[2]:02X} R3={r[3]:02X}  {flags}")

    def _print_micro_step(self, addr, sigs, bus_val, reg_idx, use_rs):
        sig_str = "+".join(sorted(sigs)) if sigs else "(none)"
        rn = "RS" if use_rs else "Rd"
        print(f"    [{addr:02X}] step={self.step} bus=0x{bus_val:02X} "
              f"sig=[{sig_str}] reg{rn}=R{reg_idx} "
              f"PC=0x{self.pc:02X} MAR=0x{self.mar:02X} "
              f"A=0x{self.a:02X} T=0x{self.temp:02X} "
              f"Z={self.flag_z} C={self.flag_c}")


#
#  Simple two-pass assembler
#

class Assembler:
    """
    Minimal two-pass assembler for the 8-bit CPU instruction set.

    Supported syntax:
        LABEL:                  define a label at the current address
        MNEMONIC                NOP, HLT
        MNEMONIC Rd, Rs         ADD, SUB, MOV
        MNEMONIC Rd, addr       LOAD, STORE
        MNEMONIC addr           JMP, JZ, JC
        .byte v1, v2, ...       raw program bytes (decimal or 0x hex)
        .ram  addr, val         pre-load data RAM at address with value
        ; comment               line comment
    """

    # Regex patterns
    RE_COMMENT  = re.compile(r";.*$")
    RE_LABEL    = re.compile(r"^(\w+):\s*$")
    RE_DIRECTIVE = re.compile(r"^\.(byte|ram)\s+(.+)$", re.IGNORECASE)
    RE_BLANK    = re.compile(r"^\s*$")

    RE_REGREG   = re.compile(
        r"^(ADD|SUB|MOV)\s+R(\d),\s*R(\d)\s*$", re.IGNORECASE)
    RE_LOAD     = re.compile(
        r"^LOAD\s+R(\d),\s*(.+)$", re.IGNORECASE)
    RE_STORE    = re.compile(
        r"^STORE\s+R(\d),\s*(.+)$", re.IGNORECASE)
    RE_ADDR_JMP = re.compile(
        r"^(JMP|JZ|JC)\s+(.+)$", re.IGNORECASE)
    RE_SINGLE   = re.compile(
        r"^(NOP|HLT)\s*$", re.IGNORECASE)

    def __init__(self):
        self.errors = []

    @staticmethod
    def _parse_num(s: str) -> int:
        s = s.strip()
        if s.startswith("0x") or s.startswith("0X"):
            return int(s, 16)
        return int(s)

    def _parse_val(self, s: str, labels: dict, line_num: int) -> int:
        s = s.strip()
        if s in labels:
            return labels[s]
        return self._parse_num(s)

    def assemble(self, source: str):
        """
        Assemble source text → (prog_rom: bytearray, data_ram: bytearray).
        """
        lines = source.splitlines()
        labels = {}
        self.errors = []

        #  Pass 1: compute addresses, collect labels
        addr = 0
        for line_num, line in enumerate(lines, 1):
            line = self.RE_COMMENT.sub("", line).strip()
            if not line:
                continue
            m = self.RE_LABEL.match(line)
            if m:
                labels[m.group(1)] = addr
                continue
            dm = self.RE_DIRECTIVE.match(line)
            if dm:
                kind = dm.group(1).lower()
                if kind == "byte":
                    # each .byte adds one byte to program ROM
                    vals = [v.strip() for v in dm.group(2).split(",")]
                    addr += len(vals)
                elif kind == "ram":
                    addr += 0   # .ram doesn't consume program space
                continue
            m = self.RE_REGREG.match(line)
            if m:
                addr += 1; continue
            m = self.RE_LOAD.match(line)
            if m:
                addr += 2; continue
            m = self.RE_STORE.match(line)
            if m:
                addr += 2; continue
            m = self.RE_ADDR_JMP.match(line)
            if m:
                addr += 2; continue
            m = self.RE_SINGLE.match(line)
            if m:
                addr += 1; continue
            self.errors.append(f"Line {line_num}: unrecognized instruction: {line}")

        if self.errors:
            return None, None

        # Pass 2: emit binary
        prog = bytearray(addr)
        data_ram = bytearray(DATA_RAM_SIZE)
        pc = 0

        for line_num, line in enumerate(lines, 1):
            line = self.RE_COMMENT.sub("", line).strip()
            if not line:
                continue
            # Skip labels
            if self.RE_LABEL.match(line):
                continue
            dm = self.RE_DIRECTIVE.match(line)
            if dm:
                kind = dm.group(1).lower()
                if kind == "byte":
                    vals = [v.strip() for v in dm.group(2).split(",")]
                    for v in vals:
                        prog[pc] = self._parse_val(v, labels, line_num) & 0xFF
                        pc += 1
                elif kind == "ram":
                    parts = [v.strip() for v in dm.group(2).split(",")]
                    if len(parts) != 2:
                        self.errors.append(f"Line {line_num}: .ram expects addr, val")
                        continue
                    ra = self._parse_val(parts[0], labels, line_num)
                    rv = self._parse_val(parts[1], labels, line_num)
                    if 0 <= ra < DATA_RAM_SIZE:
                        data_ram[ra] = rv & 0xFF
                continue

            m = self.RE_REGREG.match(line)
            if m:
                mn = m.group(1).upper()
                rd = int(m.group(2))
                rs = int(m.group(3))
                op = MNEMONIC_TO_OP[mn]
                prog[pc] = (op << 4) | (rd << 2) | rs
                pc += 1
                continue

            m = self.RE_LOAD.match(line)
            if m:
                rd = int(m.group(1))
                addr_val = self._parse_val(m.group(2), labels, line_num)
                prog[pc]   = (0b0001 << 4) | (rd << 2)
                prog[pc+1] = addr_val & 0xFF
                pc += 2
                continue

            m = self.RE_STORE.match(line)
            if m:
                rd = int(m.group(1))
                addr_val = self._parse_val(m.group(2), labels, line_num)
                prog[pc]   = (0b0010 << 4) | (rd << 2)
                prog[pc+1] = addr_val & 0xFF
                pc += 2
                continue

            m = self.RE_ADDR_JMP.match(line)
            if m:
                mn = m.group(1).upper()
                addr_val = self._parse_val(m.group(2), labels, line_num)
                op = MNEMONIC_TO_OP[mn]
                prog[pc]   = (op << 4)
                prog[pc+1] = addr_val & 0xFF
                pc += 2
                continue

            m = self.RE_SINGLE.match(line)
            if m:
                mn = m.group(1).upper()
                prog[pc] = MNEMONIC_TO_OP[mn] << 4
                pc += 1
                continue

            self.errors.append(f"Line {line_num}: unrecognized: {line}")

        if self.errors:
            return None, None
        return prog, data_ram


#
#  Test program (embedded default)
#

DEFAULT_TEST_PROGRAM = r"""
; ═══════════════════════════════════════════════════════════════════════════
;  test_program.asm — 8-bit CPU full instruction-set test
; ═══════════════════════════════════════════════════════════════════════════
;
; Pre-loaded data RAM (set via .ram directives):
;   RAM[0x80] = 0xAA    RAM[0x81] = 0x55    RAM[0x82] = 0x0F
;
; After execution, verified results in data RAM:
;   RAM[0x83] = 0xAA  <- STORE test
;   RAM[0x84] = 0xFF  <- ADD  test  (0xAA + 0x55)
;   RAM[0x85] = 0xAA  <- SUB  test  (0xFF - 0x55)
;   RAM[0x86] = 0x55  <- MOV  test
;   RAM[0x87] = 0x55  <- JZ   test (proves conditional jump worked)
;   RAM[0x88] = 0x55  <- JC   test (proves carry jump worked)

.ram 0x80, 0xAA
.ram 0x81, 0x55
.ram 0x82, 0x0F

; ── Test 1: LOAD and STORE ──────────────────────────────────────────────
LOAD  R0, 0x80          ; R0 <- 0xAA
LOAD  R1, 0x81          ; R1 <- 0x55
STORE R0, 0x83          ; RAM[0x83] <- 0xAA
LOAD  R2, 0x83          ; R2 <- 0xAA  (round-trip verify)

; ── Test 2: ADD ────────────────────────────────────────────────────────
MOV   R3, R2            ; R3 <- 0xAA
ADD   R3, R1            ; R3 <- 0xAA + 0x55 = 0xFF
STORE R3, 0x84          ; RAM[0x84] <- 0xFF

; ── Test 3: SUB ────────────────────────────────────────────────────────
SUB   R3, R1            ; R3 <- 0xFF - 0x55 = 0xAA
STORE R3, 0x85          ; RAM[0x85] <- 0xAA

; ── Test 4: MOV ────────────────────────────────────────────────────────
MOV   R0, R1            ; R0 <- 0x55
STORE R0, 0x86          ; RAM[0x86] <- 0x55

; ── Test 5: JZ (conditional jump when Zero flag set) ───────────────────
SUB   R2, R2            ; R2 <- 0, Z=1
JZ    jz_ok             ; should jump (Z is set)
HLT                     ; should NOT be reached
jz_ok:
STORE R1, 0x87          ; RAM[0x87] <- 0x55

; ── Test 6: JC (conditional jump when Carry flag set) ──────────────────
LOAD  R3, 0x82          ; R3 <- 0x0F
ADD   R3, R3            ; R3 = 0x1E,  C=0
ADD   R3, R3            ; R3 = 0x3C,  C=0
ADD   R3, R3            ; R3 = 0x78,  C=0
ADD   R3, R3            ; R3 = 0xF0,  C=0
ADD   R3, R3            ; R3 = 0xE0,  C=1  (0xF0+0xF0=0x1E0)
JC    jc_ok             ; should jump (C is set)
HLT                     ; should NOT be reached
jc_ok:
STORE R0, 0x88          ; RAM[0x88] <- 0x55

; ── Test 7: NOP and JMP (unconditional) ───────────────────────────────
NOP                     ; no effect
JMP   done              ; unconditional jump
HLT                     ; should NOT be reached
done:
HLT                     ; *** TEST COMPLETE ***
"""


#
#  Verification helpers
#

EXPECTED_RESULTS = {
    0x83: (0xAA, "STORE"),
    0x84: (0xFF, "ADD"),
    0x85: (0xAA, "SUB"),
    0x86: (0x55, "MOV"),
    0x87: (0x55, "JZ"),
    0x88: (0x55, "JC"),
}


def verify(cpu):
    """Check expected data RAM values; return (pass_count, fail_count)."""
    passed = failed = 0
    print("\n=== Result Verification ===")
    for addr, (expected, test_name) in sorted(EXPECTED_RESULTS.items()):
        actual = cpu.data_ram[addr]
        ok = actual == expected
        status = "PASS" if ok else "FAIL"
        print(f"  RAM[0x{addr:02X}] = 0x{actual:02X}  "
              f"(expected 0x{expected:02X})  [{test_name}] {status}")
        if ok:
            passed += 1
        else:
            failed += 1
    return passed, failed


def dump_ram(cpu, start=0x80, end=0x90):
    print(f"\n=== Data RAM dump 0x{start:02X}–0x{end-1:02X} ===")
    for addr in range(start, end, 16):
        hexbytes = " ".join(f"{cpu.data_ram[a]:02X}" for a in range(addr, min(addr+16, end)))
        print(f"  0x{addr:02X}: {hexbytes}")


#
#  Main
#

def find_microcode_file():
    """Search for microcode_table.csv or micro_table.csv in common locations."""
    candidates = [
        "microcode_table.csv",
        "micro_table.csv",
        "ROM/microcode_table.csv",
        "ROM/micro_table.csv",
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p
    return None


def main():
    verbose = "--trace-micro" in sys.argv
    quiet   = "-q" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("-")]

    #  Load microcode table
    mc_path = find_microcode_file()
    if mc_path is None:
        print("Error: cannot find microcode_table.csv (or micro_table.csv).")
        print("Run microcode_rom_gen.py first to generate it.")
        sys.exit(1)

    cpu = CPU()
    print(f"Loading microcode table: {mc_path}")
    cpu.load_microcode(mc_path)
    print(f"  → {len(cpu.ctrl_rom)} control-word entries loaded.")

    # Assemble program
    asm = Assembler()
    if args:
        asm_path = args[0]
        print(f"Assembling: {asm_path}")
        with open(asm_path) as f:
            source = f.read()
    else:
        print("Using embedded test program (pass a .asm file to override).")
        source = DEFAULT_TEST_PROGRAM

    prog, data_ram = asm.assemble(source)
    if asm.errors:
        print("Assembly errors:")
        for e in asm.errors:
            print(f"  {e}")
        sys.exit(1)

    # Load program and data into CPU
    cpu.prog_rom[:len(prog)] = prog
    cpu.data_ram = data_ram

    print(f"  → {len(prog)} bytes assembled, "
          f"{sum(1 for v in data_ram if v)} data RAM cells initialized.")

    # Print assembled binary
    if not quiet:
        print(f"\n=== Program ROM ({len(prog)} bytes) ===")
        for i in range(0, len(prog), 16):
            chunk = prog[i:i+16]
            hexbytes = " ".join(f"{b:02X}" for b in chunk)
            print(f"  0x{i:02X}: {hexbytes}")

    #  Execute
    print(f"\n{'='*60}")
    print(" Execution trace")
    print(f"{'='*60}")
    halted = cpu.run(verbose=not quiet, trace_micro=verbose)

    print(f"\n{'='*60}")
    if halted:
        print(f" Execution complete — HLT reached")
    else:
        print(f" Execution STOPPED (no HLT, cycle limit)")
    print(f"   Micro-steps executed : {cpu.cycles}")
    print(f"   Instructions retired: {cpu.instr_count}")
    print(f"   Registers: R0=0x{cpu.regs[0]:02X}  R1=0x{cpu.regs[1]:02X}  "
          f"R2=0x{cpu.regs[2]:02X}  R3=0x{cpu.regs[3]:02X}")
    print(f"   Flags: Z={cpu.flag_z}  C={cpu.flag_c}")
    print(f"   PC=0x{cpu.pc:02X}  MAR=0x{cpu.mar:02X}  IR=0x{cpu.ir:02X}")

    dump_ram(cpu)
    passed, failed = verify(cpu)

    print(f"\n{'='*60}")
    print(f" FINAL: {passed} passed, {failed} failed, "
          f"{passed + failed} total")
    print(f"{'='*60}")

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
