M48
; DRILL file KiCad 10.0.6-1.fc44 date 2026-09-24T17:14:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-24T17:14:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-1.fc44
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X53.999Y-34.0
X53.999Y-166.0
X205.999Y-34.0
X205.999Y-166.0
M30
